# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: teela-agent-scoring
networks:
- id: 11155111
  start_block: 7493316
  rpc_config:
    url: https://sepolia.infura.io/v3/bfebfef38464407e8b4ff77652a3eed7
  contracts:
  - name: AgentScoring
    address:
    - 0x2364Fe8d139f1A3eA88399d0217c7aCA6D712f19
    handler: src/EventHandlers.ts
    events:
    - event: BackendUpdated(address newBackend)
    - event: EscrowUpdated(address newEscrow)
    - event: ScoreRecorded(string agentId, uint256 score, uint256 revenue)
unordered_multichain_mode: false
preload_handlers: true
