name: teela-agent-scoring
description: TEELA Agent Scoring Indexer

networks:
  - id: 11155111
    start_block: 9493316
    rpc_config:
      url: https://sepolia.infura.io/v3/bfebfef38464407e8b4ff77652a3eed7
    contracts:
      - name: AgentScoring
        address:
          - "0x2364Fe8d139f1A3eA88399d0217c7aCA6D712f19"
        handler: src/EventHandlers.ts
        abi_file_path: contracts/AgentScoring.abi.json
        events:
          - event: "ScoreRecorded(string,uint256,uint256)"
          - event: "EscrowUpdated(address)"