name: teela-agent-scoring
description: TEELA Agent Scoring Indexer
networks:
  - id: 11155111
    start_block: 9493460
    contracts:
      - name: AgentScoring
        address:
          - "0x2364Fe8d139f1A3eA88399d0217c7aCA6D712f19"
        handler: src/EventHandlers.ts
        events:
          - event: ScoreRecorded(string agentId, uint256 score, uint256 revenue)
          - event: EscrowUpdated(address newEscrow)
